### PR TITLE
Migrated to CRA Typescript + File Structure Changes + Mobile View

### PR DESCRIPTION
**Pull request by cnolimit**
### What

* Migrated the project to the CRA Typescript version, using that boilerplate instead
* Updated the file structure so all related files are grouped together
* Cleaned up a few area's 

### Notes
We can go through it when you ready if you want to commit to the changes 👍🏾

### CODE REVIEW

**Comment by kylejm** [comment]
Wow man. this is so cool! Thank you so much!

## Question 1 - How? lol
So there are loads of changes here. A lot of them seem done by hand, but some of them seem like they're done by machine (e.g service worker).

Did you use some script or something to achieve any of this?

## Question 2 - Looks like there's an issue with margin on the right side of the carousel
Screenshot 2019-03-17 at 23 35 03

## Question 3 - What are the reason for the overall body margin changes?

The page used to have a consistent margin down the sides:

Screenshot 2019-03-17 at 23 37 52

Now it looks like this: 

Screenshot 2019-03-17 at 23 35 14

I think I like it when it comes to the carousel, but I'm not so sure about the footer.

Was this on purpose? What do you think?

**Comment by kylejm** [comment]
Going to get this merged because overall I like it, gimme answers to those Qs whenever you have time @cnolimit 😊.

**Comment by cnolimit** [comment]
## How?
Yeah so I basically copied the components into a new project using `create-react-app [project_name] --typescript` so some files were generated with types

## Looks like there’s an issue with margin on the right side of the carousel
 I removed the margin because If the page hits the edges ii think it makes more sense to have a images do the same

##  What are the reason for the overall body margin changes?
So  the margin in the footer normally aligns with the margins in the header, and as you don’t have one, normally I have it a few pixels aways from the viewport edges.

Another thing you could do, is create a container and set a consistent margin and apply It, to all sections, similar to what you had before but a smaller margin

**Comment by ky1ejs** [comment]
Thank @cnolimit, come visit the FC office when you have a chance! I owe you lunch! ❤️

**Pull request merged**
